spring:
  application:
    name: cim-parent
  datasource:
    url: jdbc:postgresql://db:5432/cim_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
server:
  port: 8080
nocodb:
  url: http://nocodb:8080
  api-key: your-nocodb-api-key
bbb:
  url: http://bbb:8080/bigbluebutton/api
  secret: your-bbb-secret