spring:
  application:
    name: cim-parent
  datasource:
    url: jdbc:postgresql://db:5432/cim_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # Добавлено для устранения предупреждения
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    enabled: true

server:
  port: 8080

nocodb:
  url: http://nocodb:8090
